services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  mysql:
    image: mysql:8.0
    container_name: womenSafety-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: womenSafety
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

#docker-compose up -d (file name is docker-compose)
#docker exec -it alumni-mysql mysql -u user -p (click enter. then it will ask for password)
# (container name is alumni-mysql)
#SHOW DATABASES
#USE ......
#SELECT * FROM user;
#\q (to exist)


#mailhog - localhost:8025